- app/README.md
Ensure README is sufficient for developer journey.
https://issues.corp.twilio.com/browse/VBLOCKS-1358
> [VBLOCKS-1358] docs(app): readme

- app/src/components/Button.tsx
- app/src/components/Dialpad/DialpadButton.tsx
- app/src/components/Dialpad/index.tsx
- app/src/hooks/activeCall.ts
- app/src/hooks/audioDevices.ts
- app/src/screens/Call/HangupButton.tsx
- app/src/screens/Call/HideDialpadButton.tsx
- app/src/screens/Call/MuteButton.tsx
- app/src/screens/Call/SelectAudioOutputDeviceButton.tsx
- app/src/screens/Call/ShowDialpadButton.tsx
- app/src/screens/Call/hooks.ts
- app/src/screens/Call/index.tsx
- app/src/screens/Dialer/index.tsx
- app/src/screens/TabNavigator.tsx
- app/src/store/voice/call/activeCall.ts
Isolate active call hooks from components.
https://issues.corp.twilio.com/browse/VBLOCKS-1436
> [VBLOCKS-1436] Isolate active call hooks

- app/src/screens/Dialer/BackspaceButton.tsx
- app/src/screens/Dialer/MakeOutgoingCallButton.tsx
- app/src/screens/Dialer/OutgoingRemoteParticipant.tsx
- app/src/screens/Dialer/ToggleClientInputButton.tsx
- app/src/screens/Dialer/hooks.ts
- app/src/screens/Dialer/index.tsx
- app/src/types.ts
This PR isolates dialer hooks from the dialer components.
https://issues.corp.twilio.com/browse/VBLOCKS-1451
> [VBLOCKS-1451] Isolate dialer hooks

- server/src/__tests__/routes/twiml.test.ts
- server/src/__tests__/server.test.ts
- server/src/routes/twiml.ts
- server/src/server.ts
This PR fixes the TwiML route. Manually verified with `ngrok` and client-to-client and client-to-PSTN calling.
> fix(server): twiml route params

- app/src/screens/Dialer/OutgoingRemoteParticipant.tsx
- app/src/screens/Dialer/ToggleClientInputButton.tsx
- app/src/screens/Dialer/hooks.ts
- app/src/screens/Dialer/index.tsx
- app/src/store/voice/call/outgoingCall.ts
- app/src/types.ts
This PR changes the type of `RecipientType` to `'client' | 'number'` to match what the server expects.
> [VBLOCKS-1486] Fix recipient type.

- app/src/store/voice/call/outgoingCall.ts
This PR removes the answer on bridge custom parameter when creating an outgoing call.
> [VBLOCKS-1486] Remove answer on bridge custom parameter

- app/README.md
- server/README.md
- server/package.json
> Updating branding

- app/yarn.lock
> nit: update lock file

- server/__mocks__/twilio.ts
- server/example.env
- server/src/__tests__/routes/token.test.ts
- server/src/__tests__/routes/twiml.test.ts
- server/src/__tests__/server.test.ts
- server/src/__tests__/utils/env.test.ts
- server/src/common/types.ts
- server/src/routes/twiml.ts
- server/src/utils/__mocks__/env.ts
- server/src/utils/env.ts
- server/yarn.lock
[VBLOCKS-1466](https://issues.corp.twilio.com/browse/VBLOCKS-1466)
Secure TwiML endpoint with signature validation
ref: https://www.twilio.com/blog/how-to-secure-twilio-webhook-urls-in-nodejs
> feat: secure twiml endpoint with signature validation

- .circleci/config.yml
- app/__tests__/store.test.ts
- app/src/store/voice/audioDevices.ts
This PR creates a CircleCI configuration to automatically run some tests for the Reference App and Reference Server.
> [VBLOCKS-1444] CircleCI config

- README.md
- app/README.md
- server/README.md
Readme for Auth0 3rd party auth
> [VBLOCKS-1530] Feat: readme 3 rd party auth

- app/.eslintrc.js
- app/package.json
- app/src/screens/Dialer/hooks.ts
- app/src/screens/Dialer/index.tsx
Fix some of the UX of the Dialer screen and refactor the hook logic.
> fix(app): dialer hooks refactor

- app/src/screens/Call/hooks.ts
- app/src/screens/Dialer/hooks.ts
- app/src/screens/Home/index.tsx
- app/src/screens/SignIn/index.tsx
- app/src/store/__tests__/user.test.ts
- app/src/store/user.ts
- app/src/store/voice/audioDevices.ts
- app/src/store/voice/call/activeCall.ts
- app/src/store/voice/call/outgoingCall.ts
- app/src/store/voice/token.ts
- server/.gitignore
- server/package.json
- server/src/middlewares/log.ts
- server/src/routes/token.ts
- server/src/routes/twiml.ts
- server/src/utils/log.ts
- server/yarn.lock
[VBLOCKS-1493](https://issues.corp.twilio.com/browse/VBLOCKS-1493)
SDK Errors and Warnings
- handle error cases
Server 
- try catch implementation for routes
- log request errors
> [VBLOCKS-1493] - Feature: error handling and logging

- app/.detoxrc.js
- app/config.ts
- app/e2e/login.test.js
[VBLOCKS-1617](https://issues.corp.twilio.com/browse/VBLOCKS-1617)
Fix failing detox iOS CI pipeline
> [VBLOCKS:1617] - Fix iOS detox 

- .circleci/config.yml
- server/package.json
- server/src/__tests__/server.test.ts
This PR fixes some broken types around server auth and adds a typecheck step in the CI build.
> fix(server): types and ci typecheck

- PULL_REQUEST_TEMPLETE.md
Added `PULL_REQUEST_TEMPLETE`.
> Adding PULL_REQUEST_TEMPLETE

- app/README.md
Reference the Android quickstart to detail the `google-services.json` file.
- Change README for app.
- N/A
N/A
> [VBLOCKS-1631] docs(app): android google services json info

- app/src/util/auth.ts
https://issues.corp.twilio.com/browse/VBLOCKS-1636
- logout of ID providers using `federated` logout
- Manual Validation
- 
> [VBLOCKS-1636] feat: logout user from ID providers

- CHANGELOG.md
- app/package.json
- app/src/components/__tests__/Busy.test.tsx
- app/src/screens/CallInvite/__tests__/CallInvite.test.tsx
- app/src/screens/Dialer/BackspaceButton.tsx
- app/src/screens/Dialer/__tests__/Dialer.test.tsx
- app/src/screens/Home/__tests__/Home.test.tsx
- app/src/screens/SignIn/__tests__/SignIn.test.tsx
- app/src/store/__tests__/audioDevices.test.ts
- app/src/store/__tests__/bootstrap.test.ts
- app/src/store/__tests__/registration.test.ts
- app/src/store/__tests__/token.test.ts
- app/src/store/__tests__/user.test.ts
- app/src/store/bootstrap.ts
- app/src/store/user.ts
- app/src/store/voice/audioDevices.ts
- app/src/util/__tests__/env.test.ts
- app/src/util/auth.ts
- app/yarn.lock
- server/src/__tests__/utils/log.test.ts
Added Unit tests for store and screens
- [Bulleted summary of changes]
- [eg. Updated doc]
- [eg. Added precondition to class]
> [VBLOCKS-1630] Feat: unit testing

- CHANGELOG.md
- app/package.json
- app/yarn.lock
Update the Voice SDK dependency to `1.0.0-rc6`.
- `yarn add https://github.com/twilio/twilio-voice-react-native#1.0.0-rc6`
- Manually tested outgoing call.
N/A.
> chore(app): update to @twilio/voice-react-native-sdk@1.0.0-rc6

- CHANGELOG.md
- app/package.json
- app/yarn.lock
Update the Reference App dependency on the Voice SDK to `1.0.0-beta.2`.
- `yarn add @twilio/voice-react-native-sdk@1.0.0-beta.2`
- Manually tested outgoing call.
N/A
> chore(app): update voice sdk to 1.0.0-beta.2

- .circleci/config.yml
[VBLOCKS-1797](https://issues.corp.twilio.com/browse/VBLOCKS-1797)
Upload App and Server lcov-report to Artifacts
- App: https://output.circle-artifacts.com/output/job/0fdc5b3a-4f47-4366-97ac-c4d223c25d6a/artifacts/0/app/coverage/lcov-report/index.html
- Server: https://output.circle-artifacts.com/output/job/0352bb62-665a-43a5-83cd-d23a058d3b3e/artifacts/0/server/coverage/lcov-report/index.html
> [VBLOCKS-1797] chore: upload artifacts

- app/README.md
- app/src/store/__tests__/token.test.ts
- app/src/store/voice/accessToken.ts
- app/src/store/voice/audioDevices.ts
- app/src/store/voice/registration.ts
This PR serializes errors using the `miniSerializeError` function provided by Redux Toolkit. Please note that user actions are not done in this PR, as there is further refactoring work needed as part of VBLOCKS-1834.
- Use `miniSerializeError` on errors before putting them in actions or app state.
- Manually tested outgoing calls.
Further work will be done to bring user actions up to the same standard.
> [VBLOCKS-1608] Serialize errors

- app/src/store/__tests__/audioDevices.test.ts
- app/src/store/voice/accessToken.ts
- app/src/store/voice/audioDevices.ts
- app/src/store/voice/registration.ts
[VBLOCKS-1639](https://issues.corp.twilio.com/browse/VBLOCKS-1639)
- Update `store/audioDevices` to new redux pattern
- Update `createAsyncThunk` to `createTypedAsyncThunk`
- new tests
> [VBLOCKS-1639] Refactor tech debt

- server/.gcloudignore
- server/app.yaml
[VBLOCKS-1983](https://issues.corp.twilio.com/browse/VBLOCKS-1983)
GCloud deploy configs
- [Bulleted summary of changes]
- [eg. Updated doc]
- [eg. Added precondition to class]
> [VBLOCKS-1983] Feat: gcloud deploy

- CHANGELOG.md
- app/android/app/src/main/AndroidManifest.xml
… turning off on android 30>
- [ x A visual inspection of the `Files changed` tab was made prior to submitting the pull request ensuring the style guide was followed
Android specific, updated manifest to have mic service foregrounding flag enabled for IncomingCallService. 
- Updated AndroidManifest.xml
Based on a PR on the RN codebase.
> VBLOCKS-2040: Updated android manifest to include new field to prevent mic turnoff

- app/ios/TwilioVoiceReactNativeReferenceApp.xcodeproj/project.pbxproj
- app/ios/TwilioVoiceReactNativeReferenceApp/TwilioVoiceReactNativeReferenceApp.entitlements
Adding APN entitlements file to enable iOS PushKit
- New entitlements file added to the Xcode project
- Built and ran app locally to verify that PushKit is properly initialized and returned a device token
> VBLOCKS - Adding APN entitlements file to enable iOS PushKit

- app/src/screens/ActiveCall/MuteButton.tsx
- app/src/screens/Dialer/__tests__/Dialer.test.tsx
- app/src/screens/__tests__/ActiveCall.test.tsx
[VBLOCKS-1974](https://issues.corp.twilio.com/browse/VBLOCKS-1974)
> VBLOCKS-1974 ActiveCallScreen tests.

- CHANGELOG.md
- app/__mocks__/@twilio/voice-react-native-sdk.ts
- app/package.json
- app/src/App.tsx
- app/src/store/__tests__/bootstrap.test.ts
- app/src/store/bootstrap.ts
- app/yarn.lock
This PR updates the Reference App to use `1.0.0-rc7` of the `@twilio/voice-react-native-sdk`. This PR also uses a new API introduced in the RN SDK to initialize the PushKit registry.
- Update RN SDK dependency version.
- New action for initializing the PushKit registry.
- Unit tests.
- New unit tests.
- Manual testing on iOS and Android.
Other new APIs introduced with `1.0.0-rc7` will be used/implemented in a future PR.
> chore: update @twilio/voice-react-native-sdk to 1.0.0-rc7

- CHANGELOG.md
- app/package.json
- app/yarn.lock
This PR updates the `@twilio/voice-react-native-sdk` dependency to `1.0.0-beta.3`.
- Update dependency.
- Update changelog.
- Manual testing.
N/A
> chore: update to beta.3 of the twilio rn voice sdk

- CHANGELOG.md
- README.md
- app/android/app/build.gradle
- app/ios/Podfile
- app/ios/TwilioVoiceReactNativeReferenceApp/Info.plist
- app/package.json
- app/src/util/auth.ts
- app/yarn.lock
[VBLOCKS-2060](https://issues.corp.twilio.com/browse/VBLOCKS-2060)
Auth0 Migration guide: https://github.com/auth0/react-native-auth0/blob/master/MIGRATION_GUIDE.md
- Upgrade to version 3 of react-native-auth0
> [VBLOCKS-2060] Upgrade: auth0 3.x.x

- CHANGELOG.md
- app/__mocks__/@twilio/voice-react-native-sdk.ts
- app/src/screens/StackNavigator.tsx
- app/src/screens/types.ts
- app/src/store/__tests__/bootstrap.test.ts
- app/src/store/bootstrap.ts
- app/src/store/voice/call/callInvite.ts
- app/src/util/navigation.ts
- app/src/util/setTimeout.ts
This PR consumes the new incoming call invite notification tapped event on Android platforms.
- Consume new event.
- Unit tests.
- Manual testing.
N/A
> [VBLOCKS-2058] Incoming call notification tapped event

- .circleci/config.yml
Update Slack channel config vars
- [Bulleted summary of changes]
- [eg. Updated doc]
- [eg. Added precondition to class]
> update: configs slack channel

- .circleci/config.yml
Override MY_APP_MODE to avoid using mocks
- CircleCI
- Downloaded app from AppCenter and verified the login behavior
> VBLOCKS-2117 Override MY_APP_MODE to avoid using mocks in the dogfooding app

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Update template and readme.
- Update PR template to remind collaborators to update the readme if necessary
- Update readme
- N/A
N/A
> docs: adjust github template and readme

- app/README.md
Readme for deploy to appcenter
[VBLOCKS-2205](https://issues.corp.twilio.com/browse/VBLOCKS-2205)
- [Bulleted summary of changes]
- [eg. Updated doc]
- [eg. Added precondition to class]
> [VBLOCKS-2205] feat: readme for deploying to app center

- CHANGELOG.md
- app/package.json
- app/yarn.lock
[VBLOCKS-2320](https://issues.corp.twilio.com/browse/VBLOCKS-2320)
- update rn-sdk version
> [VBLOCKS-2320] chore: update rn sdk 1.0.0-rc8

- server/README.md
https://issues.corp.twilio.com/browse/VBLOCKS-2206
- README deploy server to gcloud
> [VBLOCKS: 2206] - feat: readme deploying server to glcoud

- app/package.json
- app/yarn.lock
Updated to point to latest RC
- updated to point to latest RC
n/a
None
> VBLOCKS-2558: updated to point to latest rc

- CHANGELOG.md
- app/package.json
- app/yarn.lock
Updated to point to latest version of SDK
- Updated to point to latest
- compiled
None
> VBLOCKS-2558: updated SDK version to 1.0.0-beta.4

- app/package.json
- app/yarn.lock
https://issues.corp.twilio.com/browse/VBLOCKS-2754
For testing of CallMessage feature in iOS and Android
> chore: update sdk to rc21

- CHANGELOG.md
- README.md
- app/__mocks__/@twilio/voice-react-native-sdk.ts
- app/ios/Podfile
- app/package.json
- app/src/store/__tests__/bootstrap.test.ts
- app/src/store/bootstrap.ts
- app/yarn.lock
- docs/known-issues.md
This PR updates the SDK version to rc22 and uses the new CallInvite event API. These are all under the hood changes and should not affect the UX of the end-user.
- Update to SDK version RC22.
- Use new callinvite event api.
- Remove voice callinvite event api.
- Manual testing the following flows:
```
[x] android
[x] incoming call
[x] native accept
[x] local disconnect
[x] remote disconnect
[x] native reject
[x] js accept
[x] local disconnect
[x] remote disconnect
[x] js reject
[x] cancel
[x] home screen
[x] incoming call screen
[x] outgoing call
[x] accept
[x] local disconnect
[x] remote disconnect
[x] reject
[x] cancel
[x] ios
[x] incoming call
[x] native accept
[x] local disconnect
[x] remote disconnect
[x] native reject
[x] cancel
[x] outgoing call
[x] accept
[x] local disconnect
[x] …
```
> [VBLOCKS-2829] Update to SDK version rc23

- app/package.json
- app/yarn.lock
- [] New unit tests and integration tests have beed added
Update RN SDK to rc24
> Update: RC24

- app/ios/Podfile
- app/ios/TwilioVoiceReactNativeReferenceApp/AppDelegate.h
- app/ios/TwilioVoiceReactNativeReferenceApp/AppDelegate.mm
- app/ios/TwilioVoiceReactNativeReferenceApp/Info.plist
- app/ios/TwilioVoiceReactNativeReferenceApp/PrivacyInfo.xcprivacy
This PR updates the native iOS files for the RN Version upgrade, see the upgrade helper for details: https://react-native-community.github.io/upgrade-helper/?from=0.70.9&to=0.72.17
- N/A
- N/A
N/A
> Update RN Version - iOS files

- app/android/app/build.gradle
- app/android/app/src/debug/java/com/twiliovoicereactnativereferenceapp/ReactNativeFlipper.java
- app/android/app/src/main/AndroidManifest.xml
- app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp/MainActivity.java
- app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp/MainApplication.java
- app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp/MainReactNativeHost.java
- app/android/app/src/release/java/com/twiliovoicereactnativereferenceapp/ReactNativeFlipper.java
- app/android/build.gradle
- app/android/gradle.properties
- app/android/settings.gradle
This PR implements the changes needed for updating the RN Version, see the upgrade helper for more details: https://react-native-community.github.io/upgrade-helper/?from=0.70.9&to=0.72.17
- N/A
- N/A
N/A
> Upgrade RN Version - Android files

- .circleci/config.yml
This PR fixes the Android CI configuration to use the new CircleCI Android images that are not deprecated.
- Update the CircleCI config.
- CI.
N/A
> [VBLOCKS-3491] Fix Android CI config

- app/android/app/build.gradle
- app/android/app/src/debug/java/com/twiliovoicereactnativereferenceapp/ReactNativeFlipper.java
- app/android/app/src/main/AndroidManifest.xml
- app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp/MainActivity.java
- app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp/MainApplication.java
- app/android/app/src/main/java/com/twiliovoicereactnativereferenceapp/MainReactNativeHost.java
- app/android/app/src/release/java/com/twiliovoicereactnativereferenceapp/ReactNativeFlipper.java
- app/android/build.gradle
- app/android/gradle.properties
- app/android/settings.gradle
This PR implements the Android file changes needed for the RN Version Upgrade to `0.72.17`.
- N/A
- N/A
N/A
> feat: android files

- app/ios/TwilioVoiceReactNativeReferenceApp.xcodeproj/project.pbxproj
Add marketing version to plist using XCode.
- N/A
- N/A
N/A
> fix: add marketing version to plist

- README.md
This PR updates the yarn version referenced in the readme to be the one used when testing locally and used in CI.
- N/A
- N/A
N/A
> docs: update readme yarn version

- CHANGELOG.md
- app/android/build.gradle
- app/package.json
- app/yarn.lock
This PR updates the Twilio Voice RN SDK to 1.2.0.
- N/A
- Manual testing.
- CI pipeline green.
N/A
> feat: update twilio rn sdk to 1.2.0

- .circleci/config.yml
- app/android/app/build.gradle
- app/android/build.gradle
This PR implements the pipeline changes necessary to publish to Firebase App Distribution for the Android build.
- N/A
- Pipeline builds and publishes the Android APK for the dogfooding app to Firebase App Distribution.
N/A
> [VBLOCKS-3554] Firebase app distribution publish
